.env.SAMPLE, src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
=> copied backend for ucsb dining commons menu items from team01

frontend/package-lock.json, frontend/package.json, src/main/java/edu/ucsb/cs156/example/controllers/UCSBMenuItemReviewController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBMenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBMenuItemReviewRepository.java, src/main/resources/db/migration/changes/UCSBMenuItemReview.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBMenuItemReviewControllerTests.java
=> Copy files for Backend CRUD API

frontend/src/fixtures/ucsbMenuItemReviewFixtures
=> Jeremiahwong menuitemreview

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js, frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js, frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js
Added dining commons menu item fixture and form components. 
Storybook: https://680bf70007007d248283b8ef-dgehcwgsxp.chromatic.com/?path=/story/components-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemform--create
closes #9
=> Ethan ucsb dining commons menu item fixture + form component

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java, src/main/resources/db/migration/changes/HelpRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java
Closes #44 
Copied: HelpRequest.java, HelpRequestRepository.java, HelpRequestController.java, HelpRequestControllerTests.java, and HelpRequest.json.
=> FZ - Copied files from team01 for Backend

frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.js, frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js, frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.test.js, frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js
Added dining commons menu item table component + tests
Storybook: https://680bf70007007d248283b8ef-hzdmzfepmq.chromatic.com/?path=/docs/components-nav-appnavbar--docs 
closes #11
=> Ethan ucsb dining commons menu item table component

frontend/src/fixtures/ucsbMenuItemReviewFixtures.js, frontend/src/main/components/UCSBMenuItemReview/UCSBMenuItemReviewForm.js, frontend/src/stories/components/UCSBMenuItemReview/UCSBMenuItemReviewForm.stories.js, frontend/src/tests/components/UCSBMenuItemReview/UCSBMenuItemReview.test.js, src/main/java/edu/ucsb/cs156/example/entities/UCSBMenuItemReview.java, src/test/java/edu/ucsb/cs156/example/controllers/UCSBMenuItemReviewControllerTests.java
=> Form Component for MenuItemReview plus tests

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/main/java/edu/ucsb/cs156/example/entities/Articles.java, src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java, src/main/resources/db/migration/changes/Articles.json, src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
=> pc- Copy files for Backend CRUD API Articles from team02

frontend/src/fixtures/articlesFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/main/java/edu/ucsb/cs156/example/entities/Articles.java, src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java, src/main/resources/db/migration/changes/Articles.json, src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
Close #54 
Here I have updata fixtures for Articles
=> pc- update articles fixtures

frontend/src/main/components/UCSBMenuItemReview/UCSBMenuItemReviewTable.js, frontend/src/stories/components/UCSBMenuItemReview/UCSBMenuItemReviewTable.stories.js, frontend/src/tests/components/UCSBMenuItemReview/UCSBMenuItemReviewTable.test.js
=> table component and tests menuitemreview

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBMenuItemReview/UCSBMenuItemReviewCreatePage.js, frontend/src/main/pages/UCSBMenuItemReview/UCSBMenuItemReviewEditPage.js, frontend/src/main/pages/UCSBMenuItemReview/UCSBMenuItemReviewIndexPage.js, frontend/src/tests/pages/UCSBMenuItemReview/UCSBMenuItemReviewCreatePage.test.js, frontend/src/tests/pages/UCSBMenuItemReview/UCSBMenuItemReviewEditPage.test.js, frontend/src/tests/pages/UCSBMenuItemReview/UCSBMenuItemReviewIndexPage.test.js
=> add placeholders and edit app navbar

frontend/src/fixtures/helpRequestFixtures.js
Closes #45 
Added helpRequestFixtures in javascript, with three examples.
All examples follow json format from create data using swagger
=> Fz - created fixtures for tests

frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
Made index page for UCSB Dining Commons Menu Item.
To test:
1. Navigate to https://team02-dev-ethansolomon49.dokku-04.cs.ucsb.edu/ and log in. Then, click on "UCSB Dining Commons Menu Item" and then "Create". 
2. Fill in the fields to create your own menu item
3. It should automatically go back to https://team02-dev-ethansolomon49.dokku-04.cs.ucsb.edu/ucsbdiningcommonsmenuitem/
and see the list of all items.
4. Clicking "Delete" on an item should delete it. 
Index page storybook: https://680bf70007007d248283b8ef-osskvxyuey.chromatic.com/?path=/story/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemeditpage--default
Made edit page for UCSB Dining Commons Menu Item.
To test:
1. Navigate to https://team02-dev-ethansolomon49.dokku-04.cs.ucsb.edu/ucsbdiningcommonsmenuitem/ by logging …
=> Ethan ucsb dining commons menu item index + edit pages

.github/workflows/99-team02.yml, src/test/java/edu/ucsb/cs156/example/integration/UCSBMenuItemReviewIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBMenuItemReviewWebIT.java
Closes #79 
Closes #80 
Added integration test to test that admin can create a new review and logged in user can get by ID. 
Added end to end test that regular user cannot create review
=> Jerry team03

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganizations.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsControllerTests.java
Copied over CRUD operations from team01 for UCSBOrganizations
Closes issue #17
To test:
open app on localhost or dokku
go to swagger
Try each endpoint for api/UCSBOrganization
=> copied backend CRUD operations from team01 for UCSBOrganization table

frontend/src/fixtures/ucsbOrganizationFixtures.js, frontend/src/main/components/UCSBOrganizations/UCSBOrganizationForm.js, frontend/src/stories/components/UCSBOrganizations/UCSBOrganizationForm.stories.js, frontend/src/tests/components/UCSBOrganizations/UCSBOrganizationForm.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganizations.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsControllerTests.java
Closes issue #19 
Merge after PR #87
Added a form for the UCSB Organizations table.
Only adds form to the storybook; no integration.
To access storybook, use: https://680bf70007007d248283b8ef-lqflbrmkgb.chromatic.com/?path=/story/components-ucsborganizations-ucsborganizationform--create
=> Montgomery - Add form for UCSBOrganizations

frontend/src/fixtures/ucsbOrganizationFixtures.js, frontend/src/main/components/UCSBOrganizations/UCSBOrganizationForm.js, frontend/src/main/components/UCSBOrganizations/UCSBOrganizationTable.js, frontend/src/main/utils/UCSBOrganizationUtils.js, frontend/src/stories/components/UCSBOrganizations/UCSBOrganizationForm.stories.js, frontend/src/stories/components/UCSBOrganizations/UCSBOrganizationTable.stories.js, frontend/src/tests/components/UCSBOrganizations/UCSBOrganizationForm.test.js, frontend/src/tests/components/UCSBOrganizations/UCSBOrganizationTable.test.js, frontend/src/tests/utils/UCSBOrganizationUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganizations.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsControllerTests.java
Closes issue #20 
Merge after PR #89
Added UCSBOrganization table
https://ucsb-cs156-s25.github.io/team02-s25-04/prs/94/chromatic/
=> Montgomery ucsb organization table

frontend/src/App.js, frontend/src/fixtures/ucsbOrganizationFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/UCSBOrganizations/UCSBOrganizationForm.js, frontend/src/main/components/UCSBOrganizations/UCSBOrganizationTable.js, frontend/src/main/pages/UCSBOrganizations/UCSBOrganizationsCreatePage.js, frontend/src/main/pages/UCSBOrganizations/UCSBOrganizationsEditPage.js, frontend/src/main/pages/UCSBOrganizations/UCSBOrganizationsIndexPage.js, frontend/src/main/utils/UCSBOrganizationUtils.js, frontend/src/stories/components/UCSBOrganizations/UCSBOrganizationForm.stories.js, frontend/src/stories/components/UCSBOrganizations/UCSBOrganizationTable.stories.js, frontend/src/tests/components/UCSBOrganizations/UCSBOrganizationForm.test.js, frontend/src/tests/components/UCSBOrganizations/UCSBOrganizationTable.test.js, frontend/src/tests/pages/UCSBOrganizations/UCSBOrganizationsCreatePage.test.js, frontend/src/tests/pages/UCSBOrganizations/UCSBOrganizationsEditPage.test.js, frontend/src/tests/pages/UCSBOrganizations/UCSBOrganizationsIndexPage.test.js, frontend/src/tests/utils/UCSBOrganizationUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganizations.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationsControllerTests.java
closes issue #21 
Depends on PR #94 (I based it off that branch unnecessarily unfortunately)
Added placeholder pages for Index, Create, Edit pages for commits table.
https://team02-dev-asuasuasu1.dokku-04.cs.ucsb.edu/ucsborganizations
=> Montgomery ucsb organization placeholder pages

frontend/src/fixtures/recommendationRequestFixtures.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
=> Add fixtures for RecommendationRequest

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
Closes #28 
Form component
Link to published storybook
[https://680bf70007007d248283b8ef-lckcavgwwp.chromatic.com/](https://680bf70007007d248283b8ef-lckcavgwwp.chromatic.com/)
=> Add RecommendationRequestForm

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
=> Copy Placeholders for RecommendationRequest pages

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
closes #29 
[https://680bf70007007d248283b8ef-zcplzgzwsh.chromatic.com/?path=/story/components-recommendationrequest-recommendationrequesttable--empty](https://680bf70007007d248283b8ef-zcplzgzwsh.chromatic.com/?path=/story/components-recommendationrequest-recommendationrequesttable--empty)
=> Add RecommendationRequest table

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
closes #31 
1. visit https://team02-dev-j1yl.dokku-04.cs.ucsb.edu/
2. login
3. navigate to `recommendationrequest/create`
4. enter form fields
5. click create button
[https://680bf70007007d248283b8ef-khjpgwmime.chromatic.com/](https://680bf70007007d248283b8ef-khjpgwmime.chromatic.com/)
=> Add recommendation request create page

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
closes #32 
[https://680bf70007007d248283b8ef-uypvixuzdh.chromatic.com/](https://680bf70007007d248283b8ef-uypvixuzdh.chromatic.com/)
=> Add RecommendationRequest Index page

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/Articles/ArticlesCreatePage.js, frontend/src/main/pages/Articles/ArticlesEditPage.js, frontend/src/main/pages/Articles/ArticlesIndexPage.js, frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js, frontend/src/tests/pages/Articles/ArticlesEditPage.test.js, frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js
Closes #58 
Merge AFTER PR #102 
In this PR, I added the articles create page
The link is https://team02-renbo2004-dev.dokku-04.cs.ucsb.edu/articles/create
=> pc - add articles create page

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
closes #33 
[https://680bf70007007d248283b8ef-oununyzlqv.chromatic.com/](https://680bf70007007d248283b8ef-oununyzlqv.chromatic.com/)
=> Add recommendation request edit page

frontend/src/main/pages/Articles/ArticlesEditPage.js, frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js, frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
Closes #60 
Merge AFTER PR #109
In this PR, I added the articles edit page
The link is https://team02-renbo2004-dev.dokku-04.cs.ucsb.edu/articles
=> Renbo articles edit page

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/test/java/edu/ucsb/cs156/example/integration/ArticleIT.java, src/test/java/edu/ucsb/cs156/example/integration/ArticlesIT.java
Closes #115 
In this PR, I add the Integration test for Articles.
=> pc - add Integration test for Articles

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java, src/test/java/edu/ucsb/cs156/example/integration/ArticleIT.java, src/test/java/edu/ucsb/cs156/example/integration/ArticlesIT.java, src/test/java/edu/ucsb/cs156/example/web/ArticleWebIT.java
Closes #117 
In the PR, I added end 2 end test for Articles
=> pc - articles end 2 end test

frontend/package.json, src/test/java/edu/ucsb/cs156/example/integration/HelpRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/HelpRequestWebIT.java
Closes #120 
End to End test
- admin can edit and delete help requests
- regular user cannot create help requests
- regular user cannot see delete button
=> Fahim help request e2e tests

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java
=> Add integration test for RecommendationRequest

src/test/java/edu/ucsb/cs156/example/web/RecommendationRequestWebIT.java
=> Add E2E test for RecommendationRequest
